### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by mokkin** [ffrgb/meshviewer#140]
with the following error:
```
[00:51:23] Finished 'copy' after 21 s
[00:51:23] Starting 'html'...
[00:51:24] 'html' errored after 639 ms
[00:51:24] SyntaxError: Unexpected token ] in JSON at position 1556
    at Object.parse (native)
    at Object.transform (/var/www/html/meshviewer/gulp/tasks/html.js:11:18)
    at transformFile (/var/www/html/meshviewer/node_modules/gulp-inject/src/inject/index.js:277:35)
    at Array.reduce (native)
    at getTagsToInject (/var/www/html/meshviewer/node_modules/gulp-inject/src/inject/index.js:275:16)
    at /var/www/html/meshviewer/node_modules/gulp-inject/src/inject/index.js:126:24
    at Array.forEach (native)
    at getNewContent (/var/www/html/meshviewer/node_modules/gulp-inject/src/inject/index.js:122:19)
    at DestroyableTransform.<anonymous> (/var/www/html/meshviewer/node_modules/gulp-inject/src/inject/index.js:87:25)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
[00:51:24] 'default' errored after 34 s

```
Debian 8.8
http://karte.leipzig.freifunk.net:8018/meshviewer/build/

**Comment by xf-** [comment]
Could you provide your config.json and config.default.json.
Your build wasn't finished and config not injected

**Comment by mokkin** [comment]
Thanks for the glue! Checking my config for type errors has solved it!
