### ISSUE TITLE
Build output not working

### ISSUE THREAD

**Issue by thunderstorm99** [ffrgb/meshviewer#300]
So i just opened an issue, which was deleted by someone. I can't get the output of this repo to work. It fails using node:12.12.0-stretch.
It was pointed out to me to follow the old instructions using
```
Maybe the old documentation still works:

https://github.com/rubo77/meshviewer-doc/blob/master/build_install.md
```

However this is exactly what i did. Does someone else know what can be done about that? Also what is the process for you to host the app?
Also please don't directly delete an issue next time as I'm not really interested in writing the same issue over and over again.

Attached is the log:

```
root@98dcb72b09a0:/app# node app
/app/app.js:41
var requirejs,require,define;!function(f){function p(t,e){return n.call(t,e)}function s(t,e){var n,i,o,r,s,a,u,l,h,c,d,f=e&&e.split("/"),p=M.map,m=p&&p["*"]||{};if(t){for(s=(t=t.split("/")).length-1,M.nodeIdCompat&&k.test(t[s])&&(t[s]=t[s].replace(k,"")),"."===t[0].charAt(0)&&f&&(t=f.slice(0,f.length-1).concat(t)),h=0;h<t.length;h++)if("."===(d=t[h]))t.splice(h,1),h-=1;else if(".."===d){if(0===h||1===h&&".."===t[2]||".."===t[h-1])continue;0<h&&(t.splice(h-1,2),h-=2)}t=t.join("/")}if((f||m)&&p){for(h=(n=t.split("/")).length;0<h;h-=1){if(i=n.slice(0,h).join("/"),f)for(c=f.length;0<c;c-=1)if((o=p[f.slice(0,c).join("/")])&&(o=o[i])){r=o,a=h;break}if(r)break;!u&&m&&m[i]&&(u=m[i],l=h)}!r&&u&&(r=u,a=l),r&&(n.splice(0,a,r),t=n.join("/"))}return t}function m(e,n){return function(){var t=i.call(arguments,0);return"string"!=typeof t[0]&&1===t.length&&t.push(null),u.apply(f,t.concat([e,n]))}}function _(e){return function(t){x[e]=t}}function g(t){if(p(b,t)){var e=b[t];delete b[t],L[t]=!0,r.apply(f,e)}if(!

ReferenceError: window is not defined
    at /app/app.js:41:79584
    at define.get (/app/app.js:41:65857)
    at Object.<anonymous> (/app/app.js:41:65948)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

Thanks in advance.

**Comment by xf-** [comment]
We offer no support, because people complain about everything. This repo is only focused on ffrgb.

In your case this not an node application (only gulp used as build tool). Serve it via nginx or other webserver as static content. Loads json from datapath.

**Comment by thunderstorm99** [comment]
Okay that helped, thanks.
